apiVersion: v1
kind: Service
metadata:
  name: drycc-quickwit-searcher
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7280"
    prometheus.io/path: "/metrics"
  labels:
    app: drycc-quickwit
    heritage: drycc
    component: drycc-quickwit-searcher
spec:
  clusterIP: None
  selector:
    app: drycc-quickwit
    component: drycc-quickwit-searcher
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 7281
      targetPort: grpc
      name: grpc
