apiVersion: v1
kind: Secret
metadata:
  name: quickwit-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  {{- if (.Values.storageEndpoint) }}
  storage-lookup: {{ .Values.storageLookup | b64enc }}
  storage-bucket: {{ .Values.storageBucket | b64enc }}
  storage-endpoint: {{ .Values.storageEndpoint | b64enc }}
  storage-accesskey: {{ .Values.storageAccesskey | b64enc }}
  storage-secretkey: {{ .Values.storageSecretkey | b64enc }}
  {{- end }}
