apiVersion: v1
kind: ConfigMap
metadata:
  name: quickwit-config
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: drycc
data:
  quickwit.yaml: |
    version: 0.8

    grpc:
      max_message_size: 10 MiB

    metastore_uri: ${DRYCC_DATABASE_URL}
    default_index_root_uri: s3://${DRYCC_STORAGE_BUCKET}/indexes

    storage:
      s3:
        access_key_id: ${DRYCC_STORAGE_ACCESSKEY}
        secret_access_key: ${DRYCC_STORAGE_SECRETKEY}
        region: ${AWS_REGION:-us-east-1}
        endpoint: ${DRYCC_STORAGE_ENDPOINT}
        force_path_style_access: ${QW_S3_FORCE_PATH_STYLE_ACCESS:-false}
        disable_multi_object_delete: false
        disable_multipart_upload: false

    metastore:
      postgres:
        min_connections: 0
        max_connections: 10
        acquire_connection_timeout: 10s
        idle_connection_timeout: 10min
        max_connection_lifetime: 30min

    indexer:
      enable_otlp_endpoint: ${QW_ENABLE_OTLP_ENDPOINT:-true}
      split_store_max_num_bytes: 100G
      split_store_max_num_splits: 1000
      max_concurrent_split_uploads: 12

    ingest_api:
      max_queue_memory_usage: 2GiB
      max_queue_disk_usage: 4GiB
      content_length_limit: 10MiB

    searcher:
      fast_field_cache_capacity: 1G
      split_footer_cache_capacity: 500M
      partial_request_cache_capacity: 64M
      max_num_concurrent_split_streams: 100
      max_num_concurrent_split_searches: 100
      aggregation_memory_limit: 500M
      aggregation_bucket_limit: 65000
      split_cache:
         max_num_bytes: 1G
         max_num_splits: 10000
         num_concurrent_downloads: 1

    jaeger:
      enable_endpoint: ${QW_ENABLE_JAEGER_ENDPOINT:-true}

  log-indexes-template.json: |
    {
      "version": "0.9",
      "template_id": "{{ .Values.logIndexTemplateName }}",
      "description": "kubernetes container logs",
      "index_id_patterns": [
        "{{ .Values.logIndexPrefix }}*"
      ],
      "priority": 100,
      "doc_mapping": {
        "mode": "dynamic",
        "dynamic_mapping": {
          "indexed": true,
          "stored": true,
          "tokenizer": "raw",
          "record": "basic",
          "expand_dots": true,
          "fast": true
        },
        "field_mappings": [{
            "name": "log",
            "type": "text",
            "tokenizer": "default",
            "record": "position"
          },
          {
            "name": "timestamp",
            "type": "datetime",
            "description": "Time at which the event was emitted",
            "input_formats": [
              "rfc3339",
              "unix_timestamp"
            ],
            "output_format": "unix_timestamp_secs",
            "stored": true,
            "indexed": true,
            "fast": true,
            "fast_precision": "milliseconds"
          },
          {
            "name": "kubernetes",
            "type": "object",
            "field_mappings": [{
                "name": "namespace_name",
                "type": "text",
                "tokenizer": "raw",
                "fast": true
              },
              {
                "name": "pod_name",
                "type": "text",
                "tokenizer": "raw",
                "fast": true
              },
              {
                "name": "docker_id",
                "type": "text",
                "tokenizer": "raw",
                "fast": true
              },
              {
                "name": "container_name",
                "type": "text",
                "tokenizer": "raw",
                "fast": true
              }
            ]
          }
        ],
        "tag_fields": [
          "kubernetes.namespace_name"
        ],
        "timestamp_field": "timestamp",
        "index_field_presence": true
      },
      "search_settings": {
        "default_search_fields": [
          "log"
        ]
      },
      "retention": {
        "period": "{{ .Values.logIndexRetention }}",
        "schedule": "daily"
      }
    }
